[book]
title = "deltacv docs"
authors = ["Sebastian Erives"]
language = "en"
description = "Official documentation hub for all deltacv projects — PaperVision and EOCV-Sim."
src = "src"
    
[build]
build-dir = "../dist"

[output.html]
additional-css = ["custom.css"]